title: flexits personal page
description: A portfolio page describing my projects and achievements
author: Alexander Korostelin
avatar: /assets/logo.jpeg
#email: 4d.41.49.4c@gmail.com
location: West Siberia
university: Siberian State University of Telecommunications and Informatics

subscribe: false

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
