title: flexits personal page
description: A portfolio page describing projects and achievements
author: Alexander Korostelin
avatar: /logo.jpeg
#email: 4d.41.49.4c@gmail.com
location: West Siberia

subscribe: false

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

collections:
  publications:
    output: true
    permalink: /publications/:path/

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

